spring:
  application:
     name: restaurant-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
        defaultZone: http://discovery:8761/eureka/

server:
  port: 8081
