spring:
  application:
     name: restaurant-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
        defaultZone: ${DISCOVERY_ZONE}

server:
  port: 8081
